### ISSUE TITLE
Could you create an example to demonstrate how to this client to consume google oauth2?

### ISSUE THREAD

**Issue by zxkane** [pwheel/spring-security-oauth2-client#5]
This library looks nice. But it's a bit difficult for me to understand how consuming it in my project for google oauth2 login. Could you create an example to demonstrate it?

Thanks.

**Comment by pwheel** [comment]
Hi, sorry for the slow response.

There is an example of configuring the library for use with Google on the README page. The library has been used with Google; some changes were contributed back to it.
Some familiarity with Spring Security is assumed.

Have you reviewed the README?
