### ISSUE TITLE
App Example

### ISSUE THREAD

**Issue by wie88** [pwheel/spring-security-oauth2-client#7]
Sorry for contacting you throught issue, 

I'm trying to use your project as my authentication provider but i found some difficulties in implementing your project.. i think i miss something but i don't really sure about what i have missed. would you like to share me some project that is successfully implement this project?

Thanks,

**Comment by pwheel** [comment]
Hi, sorry I didn't reply very promptly. You've closed this, are you sorted now?

Cheers

**Comment by wie88** [comment]
yeah.. I tried for sometime and i found my mistakes. thanks for your library. it is very useful.
